UniverseStop/FE

next.config.js
package.json
src/components/chat/ChatList.tsx
src/components/chat/ChatNav.tsx
src/pages/api/auth/[...nextauth].ts
src/pages/api/chat.ts
src/pages/chat/[room].tsx
src/pages/chat/index.tsx
src/styles/globals.css
yarn.lock

[Remove]chat component remove

---

src/components/Layout.tsx
src/components/layout.module.css
src/components/nav/Nav.tsx
src/components/nav/nav.module.css
src/pages/api/auth/[...nextauth].ts
src/pages/api/customaxios.tsx
src/pages/api/rest.ts
src/pages/chat/index.tsx
src/pages/index.tsx
src/pages/main/index.tsx
src/pages/main/main.module.css
src/pages/users/kakaoredirect.tsx
src/pages/users/login.tsx
src/styles/globals.css
tailwind.config.ts

[Design] navbar design

---

src/pages/aboutus/aboutus.module.css
src/pages/aboutus/index.tsx
src/styles/globals.css

[Layout] aboutUs layout

---

src/pages/aboutus/aboutus.module.css
src/pages/aboutus/index.tsx

[Fix] aboutUs css Fix

---

public/images/back.svg
public/images/search.svg
src/pages/search/index.tsx

[Layout] search css

---

src/components/post/PostDetail.tsx
src/pages/aboutus/index.tsx
src/types/postTypes.d.ts

[Features] aboutus 슬라이더 추가

---

src/pages/api/post.ts
src/pages/detail/[id]/index.tsx
src/types/postTypes.d.ts
src/utils/getCategory.tsx
tailwind.config.ts

[Layout] post detail css

---

package-lock.json
package.json
src/components/post/PostDetail.tsx
src/pages/aboutus/imageSlider/index.tsx
src/pages/aboutus/index.tsx
yarn.lock

[Features] aboutus slide

---

src/components/post/PostDetail.tsx
src/pages/aboutus/imageSlider/index.tsx
src/pages/aboutus/index.tsx

[Layout] aboutus css

---

src/components/Layout.tsx
src/components/category/Category.tsx
src/components/category/CategoryBtn.tsx
src/components/mypage/Introduce.tsx
src/components/mypage/MyPost.tsx
src/components/user-input/UserInput.tsx
src/pages/create-post/index.tsx
src/pages/main/index.tsx
src/pages/mypage/edit/index.tsx
src/pages/mypage/index.tsx
src/pages/userinfo-setting/index.tsx

createPost 부분은 아직 미완성!
디자인 수정이 있어서 팀원들에게 의견 취합후 layout 같은 브런치에서 작업할 예정

[Layout]mypageEdit, userInfoSetting page 완료

---

src/components/aboutus/ImageSlider.tsx
src/components/detail/DeleteModal.tsx
src/components/detail/KakaoMap.tsx
src/pages/aboutus/index.tsx
src/pages/api/post.ts
src/pages/detail/[id]/index.tsx

[Features] post detail

---

src/pages/assessment/index.tsx

[Features] assessment css

---

src/components/category/Category.tsx
src/components/category/CategoryBtn.tsx
src/components/user-input/UserInput.tsx
src/pages/api/user.ts
src/pages/create-post/index.tsx
src/pages/mypage/[id].tsx
src/pages/mypage/edit/index.tsx
src/pages/userinfo-setting/index.tsx
src/pages/users/kakao/kakaoredirect.tsx
src/types/myPageTypes.d.ts
src/utils/getCategory.tsx
tailwind.config.ts

라우터설정, 중복확인, 토큰 업데이트, 유저정보세팅(초기로그인시) 완료

[Features] initial-setting 완료

---

src/components/manager/Management.tsx
src/pages/api/manager.ts

[Features] management

---

src/components/manager/Management.tsx
src/pages/api/manager.ts
src/pages/manager/index.tsx
src/types/managerTypes.d.ts
tailwind.config.ts

[Features] management 타입 추가 및 변수 이름 변경

---

src/pages/_error.tsx

[Features] error 이전 페이지로 이동 기능 구현

---

src/components/main/Search.tsx
src/hooks/useInput.ts

[Features] search 추천 검색어 기능 구현 및 css 변경

---

src/components/detail/ChatApplication.tsx
src/components/detail/DeleteModal.tsx
src/components/detail/KakaoMap.tsx
src/components/detail/Post.tsx
src/components/detail/UserInfo.tsx
src/utils/convertTime.tsx

[Features] 게시물 상세 css 개선 및 유저 마이페이지 연결

---

src/components/detail/ChatParticipate.tsx

[Features] 정류장 상세 참가 수락 및 거절 기능 완성

---

package.json
src/components/Layout.tsx
src/components/detail/Post.tsx
src/components/detail/UserInfo.tsx
src/components/nav/Nav.tsx
src/context/KakaoContext.tsx
src/pages/_app.tsx
src/pages/aboutus/index.tsx
src/pages/api/rest.ts
src/pages/users/kakao/kakaoredirect.tsx
src/recoil/atoms/currentUser.tsx
src/types/userTypes.d.ts
src/utils/convertTime.tsx
src/utils/getCurrentUser.tsx
yarn.lock

[Features] recoil 적용

---

src/pages/aboutus/index.tsx

[Features] recoil 초기화 함수 변경

---

src/components/detail/ChatParticipate.tsx
src/pages/search/index.tsx

[Features] 추천 검색어 기능 추가 및 UI 개선

---

src/pages/aboutus/index.tsx

[Features] 브라우저 닫기 시 리코일 저장소 초기화

---

src/components/manager/Management.tsx
src/components/manager/Statistics.tsx
src/components/manager/common/ManagementTable.tsx
src/pages/api/manager.ts

[Features] 관리자 페이지 사용자 차단 및 구제 기능

---

src/components/Layout.tsx
src/components/manager/Management.tsx
src/components/manager/common/ManagementModal.tsx
src/components/manager/common/ManagementTable.tsx
src/pages/api/manager.ts
src/types/managerTypes.d.ts

관리자 페이지 사용자 관리 기능 추가 (사용자 상세 정보 모달)

[Features] 관리자 페이지 사용자 관리 기능 추가 (사용자 상세 정보 모달)

---

src/components/common/PostPreview.tsx

[Fix] 날짜 잘못가져오는 내용 개선

---

next.config.js
src/components/common/PostPreview.tsx
src/components/nav/Nav.tsx
src/hooks/useChat.ts
src/pages/api/post.ts
src/pages/api/user.ts
src/pages/manager/index.tsx
src/pages/search/index.tsx

관리자 페이지 접근 권한 설정 및 관리자 페이지 이동 버튼 추가

[Features] 관리자 페이지 접근 권한 설정 및 관리자 페이지 이동 버튼 추가

---

src/pages/assessment/index.tsx
src/pages/create-post/index.tsx
src/pages/mypage/edit/index.tsx
src/pages/user-report/[id].tsx
src/pages/userinfo-setting/index.tsx
src/utils/confirmPermissions.tsx

[Features] 페이지 접근 권한 설정 (로그인 사용자)

---

src/pages/users/kakao/kakaoredirect.tsx

[Fix] 유효성 추가

---

src/components/detail/KakaoMap.tsx
src/components/detail/Post.tsx
src/pages/aboutus/index.tsx
src/types/postTypes.d.ts

게시물 상세 지도 주소, 위도, 경도로 찾도록 변경
토큰 유효성 추가 (유효하지 않는 토큰의 경우 초기화되도록)

[Features] 게시물 상세 지도 주소, 위도, 경도로 찾도록 변경 및 토큰 유효성 추가

---

src/components/create-post/AddLocation.tsx
src/components/manager/common/LineChart.tsx
src/components/manager/common/StatisticsMap.tsx
src/pages/api/instance.ts
src/pages/api/manager.ts
src/pages/main/index.tsx
src/pages/manager/index.tsx

[Fix] 관리자 페이지 오류 수정

---

src/components/common/PostPreview.tsx
src/pages/aboutus/index.tsx

[Fix] 리코일 초기화 조건문 변경

---

src/components/calendar/Calendar.tsx
src/components/create-post/AddLocation.tsx
src/components/manager/common/StatiscticsDoughnut.tsx
src/components/manager/common/StatisticsMap.tsx
src/pages/api/manager.ts
src/pages/create-post/index.tsx
src/pages/manager/index.tsx
src/pages/search/index.tsx
src/types/managerTypes.d.ts

[Features] 관리자 페이지 위치 통계 구현

---

public/images/back.svg
public/images/backWhite.svg
src/components/common/Back.tsx
src/pages/search/index.tsx

[Refactor] 검색 페이지 css 개선 및 뒤로가기 버튼 추가

---

src/components/detail/KakaoMap.tsx

[Refactor]게시물 상세 지도 내 주소 css 개선

---

package.json
src/components/user-input/UserInput.tsx
yarn.lock

사용자 설정 css 개선 및 react-select 사용

[Refactor] 사용자 설정 css 개선 및 react-select 사용

---

src/pages/users/login.tsx

[Refactor] 불필요한 로직 제거
